// garenData.js — Base de données de matchups pour Garen.
// Contenu rédigé par l'auteur du projet (guide personnel, notation adaptée en Q/W/E standard).
// Rappel des sorts de Garen : Q = Frappe décisive, W = Courage, E = Jugement, R = Jugement Dernier.
//
// rating (échelle de matchup) :
//   "win"            -> favorable pour Garen
//   "skill_garen"    -> équilibré mais avantage Garen si bien joué
//   "skill_even"     -> matchup 50/50, dépend du niveau des deux joueurs
//   "skill_opponent" -> équilibré mais avantage l'adversaire si bien joué
//   "lose"           -> défavorable pour Garen

export const GAREN_ABILITIES = {
  Q: "Frappe décisive",
  W: "Courage",
  E: "Jugement",
  R: "Jugement Dernier",
};

export const RATING_META = {
  win:            { label: "Favorable",              color: "#3fb950" },
  skill_garen:    { label: "Skill – avantage Garen",  color: "#7fd858" },
  skill_even:     { label: "Équilibré",                color: "#e3b341" },
  skill_opponent: { label: "Skill – avantage adverse", color: "#f0883e" },
  lose:           { label: "Défavorable",              color: "#f85149" },
};

// name: nom d'affichage utilisé pour matcher le champion via ddragon.findChampionId()
export const GAREN_MATCHUPS = [
  {
    name: "Aatrox", rating: "skill_even", laning: "Moyenne-difficile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Au choix",
    tips: "Ton Q te permet de sortir de sa zone d'empowerment. Surveille sa régénération passive et évite ses Q en restant proche de lui plutôt qu'à distance. Reste prudent face à son potentiel de 1v2 pendant les ganks.",
    howTo: "Punis-le aux niveaux 1 à 3, sa période la plus faible. Les trades early tournent autour du placement et du timing de ses cooldowns. Après le niveau 6 le 1v1 est plus dur en pleine vie, mais tu prends l'avantage au scaling grâce à ta mobilité.",
    video: "https://youtu.be/q33rNxi54pw",
  },
  {
    name: "Akali", rating: "skill_even", laning: "Moyenne-difficile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier ou Doran épée",
    tips: "Ton E traverse son nuage (Shroud) et ton Q la ralentit. Fais-la gaspiller ses Q, coûteux en énergie. Tourne autour d'elle pendant ton E pour la forcer à te rater.",
    howTo: "Avant le niveau 6, évite le poke inutile et trade quand elle manque d'énergie. Après le 6, l'issue dépend surtout de sa capacité à esquiver ton E — un seul combo peut suffire dans un sens comme dans l'autre. Tu as un net avantage au scaling.",
    video: null,
  },
  {
    name: "Akshan", rating: "skill_even", laning: "Difficile",
    skillOrder: "Q > W > E", altSkillOrder: "W > Q > E",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Son grappin a un délai de déclenchement : all-in en deux temps si possible. Reste vigilant sur son invisibilité et n'oublie pas sa passive de résurrection en teamfight.",
    howTo: "Joue très safe en early, concède du CS si nécessaire. Évite d'être bas en vie proche de lui, il excelle pour diver. Tu scales largement mieux sur la durée.",
    video: null,
  },
  {
    name: "Ambessa", rating: "skill_opponent", laning: "Moyenne-difficile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier ou Doran épée",
    tips: "Son deuxième Q inflige un critique sur le premier ennemi touché aux extrémités du sort : évite de te placer dans son W après un combo. Serpent's Fang est un bon troisième item défensif contre elle.",
    howTo: "Abuse de ses cooldowns longs et de sa faiblesse avant son premier retour en base. Mets la pression tôt avant que son scaling AD ne prenne le dessus. Surveille bien le spacing : elle manque de sustain.",
    video: null,
  },
  {
    name: "Anivia", rating: "skill_garen", laning: "Facile-moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Les bottes de célérité sont précieuses ici. Son œuf est difficile à punir sans ton E. Utilise ton W si tu ne peux pas esquiver son Q — ton Q annule d'ailleurs son ultime.",
    howTo: "Son mana et ses dégâts early sont ses grosses faiblesses. Bloque la lane quand elle est à sec de mana. Farme proprement, évite le poke, et exploite ses limites de ressource — elle prend le dessus au scaling.",
    video: null,
  },
  {
    name: "Aurora", rating: "lose", laning: "Très difficile",
    skillOrder: "Q > W > E", altSkillOrder: "W > Q > E",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Envisage des runes de scaling HP et 2-3 points dans ton W tôt. Ses hitboxes sont généreuses, fais attention à son invisibilité.",
    howTo: "La lane est extrêmement difficile : esquive un maximum de sorts et concède du CS si besoin. Un rush résistance magique est à envisager. Un lane à égalité est déjà une victoire — l'avantage vient après la phase de lane.",
    video: null,
  },
  {
    name: "Camille", rating: "lose", laning: "Moyenne-difficile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran épée",
    tips: "Utilise toujours ton W pour réduire le stun/burst quand elle engage à l'E. Quand elle active son W, traverse-le avec ton Q pour rester au contact.",
    howTo: "Tout tourne autour de la gestion de sa passive. Force-la à l'utiliser avant de trader. Garde la wave au centre ou évite les freezes. Les niveaux 6 et 11 sont tes meilleures fenêtres de kill.",
    video: "https://youtu.be/Ugo1YF9gBVA",
  },
  {
    name: "Cassiopeia", rating: "lose", laning: "Difficile",
    skillOrder: "Q > W > E", altSkillOrder: "W > Q > E",
    summoners: "Flash / Ignite / Ghost", starterItem: "Doran bouclier",
    tips: "Elle a peu d'armure en early. Ses Q sont prévisibles, anticipe-les. Flash pour engager si tu es mal placé.",
    howTo: "Esquive ses Q, punis ses erreurs de placement, cherche un engage au Flash quand c'est possible. Farme prudemment pendant la lane et surveille son mana comme indicateur clé.",
    video: "https://youtu.be/AU2yQCsYWMU",
  },
  {
    name: "Cho'Gath", rating: "skill_garen", laning: "Moyenne",
    skillOrder: "E > Q > W", altSkillOrder: "Q > E > W",
    summoners: "Flash / Ignite", starterItem: "Doran épée ou Casque de faucheur",
    tips: "Utilise ton Q juste avant son Q qui ralentit. Son farm alimente sa régénération, mets la pression après un bon trade. Profite s'il commence Doran bouclier plutôt qu'anneau.",
    howTo: "Avant le 6, tu gagnes largement la lane si tu évites le poke inutile. Après le 6, méfie-toi de sa passive liée à l'ultime : cherche à freezer et punir ses avancées. Utilise ta mobilité en mid-game pour peser sur la carte.",
    video: null,
  },
  {
    name: "Darius", rating: "lose", laning: "Très difficile",
    skillOrder: "Q > E > W", altSkillOrder: "Q > W > E",
    summoners: "Flash / Ignite", starterItem: "Doran épée ou Doran bouclier",
    tips: "Il est moins dangereux au corps-à-corps qu'à distance de son grappin. Tes chances sont meilleures à 50% de vie qu'à 100%. Tourne sous son E pour éviter le grappin, et reste du côté opposé à ton allié en 2v1.",
    howTo: "Évite les buissons au niveau 1. Avance avec la wave. Utilise ton Q pour purger son ralentissement et engage à l'E. Reste près de ta tourelle pour pouvoir désengager. Concède du CS si nécessaire.",
    video: "https://youtu.be/OmO7t4rNwQw",
  },
  {
    name: "Dr. Mundo", rating: "win", laning: "Très facile",
    skillOrder: "E > Q > W", altSkillOrder: "Q > E > W",
    summoners: "Flash / Ignite", starterItem: "Doran épée ou Casque de faucheur",
    tips: "Reste derrière tes sbires pour éviter l'alignement de son Q. Bloque les tirs de canon avec ton positionnement.",
    howTo: "Exploite sa faiblesse des niveaux 1 à 5. Pousse légèrement pour forcer les transitions de niveau en ta faveur. Abuse de ses tentatives de farm et trade de la vie — tu gagnes presque toujours. Après son premier retour en base, il devient plus coriace.",
    video: "https://www.youtube.com/watch?v=vXDvTaOGuCw",
  },
  {
    name: "Fiora", rating: "lose", laning: "Moyenne-difficile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier ou Doran épée",
    tips: "Accepte parfois un Q pour laisser les sbires casser un freeze. Feinte ton Q pour la pousser à gaspiller sa parade. Éloigne-toi de ses points faibles pour les faire réapparaître ailleurs.",
    howTo: "La lane est un vrai duel de skill qui dépend de son placement et de l'activation de sa passive — tu peux la gagner. En mid/late game, reste vigilant sur son potentiel de split push avec deux ralentissements.",
    video: "https://www.youtube.com/watch?v=LUSYOxq--OU",
  },
  {
    name: "Gangplank", rating: "skill_even", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "W > Q > E",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Détruire ou anticiper ses tonneaux est la clé du matchup. Attention aux tonneaux cachés en buisson. Prends en compte son agrume pendant un all-in — il a beaucoup de ralentissements, approche prudemment.",
    howTo: "Avant le 6, punis-le si tu arrives à faire rater ses tonneaux ou si tu peux l'approcher. Après le 6, tu le tues souvent si tu l'atteins sans être bas en vie. Ce matchup dépend beaucoup du niveau du Gangplank en face.",
    video: null,
  },
  {
    name: "Gnar", rating: "lose", laning: "Moyenne-difficile",
    skillOrder: "Q > E > W", altSkillOrder: "Q > W > E",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Son saut a un cooldown de 20+ secondes : Mini Gnar est vulnérable ensuite. Surveille ses buffs de vitesse (Fer-de-lance rend la poursuite difficile). Fais des petits pas pour éviter son double-saut.",
    howTo: "Tu gagnes le niveau 1. Punis le surextension du Mini Gnar (portée courte), sinon contiens la lane. Méga Gnar est globalement plus fort. Ce matchup dépend beaucoup du niveau du joueur adverse.",
    video: "https://youtu.be/SsJHO_c8UO0",
  },
  {
    name: "Gragas", rating: "skill_garen", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Au choix entre les trois items de départ",
    tips: "Esquive son E sur les côtés en anticipant. Surveille son positionnement pour son ultime. Utilise ton Q juste avant d'être poussé pour éviter une réactivation. Ton W réduit la durée de son stun.",
    howTo: "Il manque de mana avant son premier retour en base : abuse-en si tu peux avancer. Après ses items, tout dépend du poke et du spacing des deux côtés. Joue bien les interactions et attends une ouverture pour l'all-in.",
    video: null,
  },
  {
    name: "Graves", rating: "win", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "Q > W > E",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Reste derrière tes sbires pour éviter ses tirs.",
    howTo: "Son gameplay repose sur le push de wave : il ne peut pas te tuer et toi non plus, sauf grosse erreur. Farme proprement et punis-le dès qu'une occasion de kill se présente.",
    video: null,
  },
  {
    name: "Gwen", rating: "skill_garen", laning: "Moyenne",
    skillOrder: "E > Q > W", altSkillOrder: "Q > E > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier ou Doran épée",
    tips: "Évite le centre de son Q, le plus dangereux. Tourne autour d'elle pendant ton E pour esquiver le maximum de Q. Surveille la régénération de son ultime et évite les trades longs qui jouent en sa faveur.",
    howTo: "Joue autour du timing de ses cooldowns, tu devrais gagner les 1v1. N'hésite pas à multiplier les phases d'engage. La gestion de ton W minimise le poke pendant les trades. Si elle prend l'avantage, elle peut snowballer vite.",
    video: null,
  },
  {
    name: "Heimerdinger", rating: "skill_opponent", laning: "Difficile",
    skillOrder: "Q > E > W", altSkillOrder: "Q > W > E",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Prioriser sa tourelle boostée est souvent la meilleure option.",
    howTo: "Il va pousser de toute façon, il y a peu de recours à part encaisser la lane. Utilise ton Flash pour rentrer pendant les ganks alliés. Le matchup devient plus jouable en avançant dans la partie.",
    video: null,
  },
  {
    name: "Illaoi", rating: "skill_even", laning: "Moyenne-difficile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran épée",
    tips: "Recule si tu ne peux pas la tuer avant que son ultime touche les tentacules. Recule généralement dès que son E te touche. Ton Q purge le ralentissement et esquive une tentacule après une malédiction.",
    howTo: "Tout le matchup tourne autour de l'esquive de son E : s'il te touche c'est souvent la défaite, si tu l'esquives c'est la sécurité et une occasion de trade. Détruire les tentacules quand c'est possible compte beaucoup.",
    video: null,
  },
  {
    name: "Irelia", rating: "skill_garen", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran épée ou Casque de faucheur",
    tips: "Déplace-toi dans la direction opposée à son stun E, ça marche souvent. Surveille ses stacks de passive et ses patterns de dash pour éviter les surprises.",
    howTo: "L'early dépend de sa capacité à te toucher avec son E. Si elle gagne le tempo, évite de trader. Fais attention au spike de son Botrk. Ne trade généralement pas sans dégât de kill ou moyen de fuir rapidement. Tu scales mieux qu'elle.",
    video: null,
  },
  {
    name: "Jax", rating: "win", laning: "Moyenne",
    skillOrder: "E > W > Q", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Casque de faucheur ou Doran épée",
    tips: "Utilise ton W quand il saute ou active son stun pour optimiser la réduction de dégâts. Ne le tape pas sous ton E avec des autos-attaques, son stun fait plus mal. Utilise ton E pendant son E à lui.",
    howTo: "Trade pour désengager après ton E. Le niveau 6 simplifie beaucoup les kills. Trader avant que son ultime ne soit disponible réduit son utilité. Investis 3 points dans ton W après avoir maxé ton E. Une build Trinity Force est plus simple à jouer qu'un Botrk.",
    video: "https://www.youtube.com/watch?v=NInPVb9zlF4",
  },
  {
    name: "Jayce", rating: "lose", laning: "Difficile",
    skillOrder: "Q > E > W", altSkillOrder: "Q > W > E ou W en premier",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "All-in quand il passe en forme distance (il ne peut pas repasser en mêlée immédiatement). Cache-toi en buisson après un push pour profiter du bonus de son Q. Positionne-toi entre lui et sa fuite pour empêcher son dash.",
    howTo: "Un Jayce Conquérant/Électrocution est plus dangereux qu'un Phase Rush. Avant le 6, c'est difficile si son spacing est bon ; son ultime augmente encore la menace. Punis ses erreurs. Tu scales, mais le matchup dépend surtout du niveau des deux joueurs.",
    video: null,
  },
  {
    name: "Karma", rating: "skill_even", laning: "Moyenne",
    skillOrder: "Q > W > E", altSkillOrder: "Q > E > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier ou Casque de faucheur",
    tips: "Évite de te faire piéger dans son combo W-R de soin.",
    howTo: "Il y a peu à faire à part trader brièvement. Difficile à tuer si elle joue bien : elle manque de burst pour te tuer. Cherche les fenêtres où ses cooldowns sont gaspillés pour trader au contact. Si elle joue Conquérant, surveille les procs de runes. Proxy la wave si la lane s'enlise, la différence se fait souvent en mid-game.",
    video: null,
  },
  {
    name: "Kayle", rating: "lose", laning: "Moyenne-difficile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Au niveau 6, elle gagne un Q et des outils de kite via son W. Utilise ton ultime après son silence, si tu ne peux pas la tuer sans, ou juste après le sien. Anticipe ton R pendant son ultime pour un dégât retardé.",
    howTo: "Elle est faible aux niveaux 2 à 5 et forte au niveau 6. Attends-toi à beaucoup de kite. Entre le niveau 6 et 12, son ultime a un cooldown 40+ secondes plus long : exploite ce timing. Elle finit par prendre l'avantage au scaling.",
    video: "https://youtu.be/XeNWKpOT-L4",
  },
  {
    name: "Kennen", rating: "lose", laning: "Difficile",
    skillOrder: "Q > E > W", altSkillOrder: "Q > W > E",
    summoners: "Flash / Ignite / Ghost / Téléportation", starterItem: "Doran bouclier",
    tips: "Surveille ton positionnement en teamfight, il excelle en flanc. Reste derrière tes sbires pour éviter ses Q.",
    howTo: "Fais attention à ses autos-attaques boostées. L'early est difficile : survis et punis la surextension. Proxy la wave permet d'éviter une lane trop compliquée. Choisis tes summoners selon ta préférence.",
    video: null,
  },
  {
    name: "Kled", rating: "skill_garen", laning: "Moyenne-difficile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran épée ou Casque de faucheur",
    tips: "Ton W peut encaisser son E, ou tu peux désengager quand il l'utilise. Il roam bien, signale-le vite à ton équipe. Burst-le une fois démonté pour le punir.",
    howTo: "Il est puissant en early et scale moins bien. Évite de mourir, il snowballe fort. Le niveau 6 t'aide. Surveille les setups de dive. Sans ton W tu es vulnérable face à lui.",
    video: null,
  },
  {
    name: "K'Sante", rating: "skill_garen", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran épée ou Casque de faucheur",
    tips: "Ses Q se baitent et s'esquivent assez facilement. Il se repositionne beaucoup avec son kit. Sa forme ultime a un E qui inflige de lourds dégâts, l'esquive est indispensable.",
    howTo: "Avantage en early avant son premier retour en base, ensuite il prend le dessus jusqu'à son 3e-4e item. N'utilise pas ton ultime en pleine vie, temporise si besoin. Surveille le timing de son Q3 même sous tourelle. Contrôle les teamfights.",
    video: "https://www.youtube.com/watch?v=NInPVb9zlF4&t=1496s",
  },
  {
    name: "Malphite", rating: "skill_even", laning: "Facile-moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier si comète, Casque de faucheur si Grasp",
    tips: "Son E n'affecte pas le nombre de rotations de ton E. Son ultime peut préparer un gank ennemi. Esquive sa comète grâce au bonus de vitesse de ton Q. Le Tranchoir Noir est un bon item contre lui.",
    howTo: "Tu peux abuser du matchup en early. Signale ses roams. C'est un matchup assez basique dont l'issue dépend surtout de ton potentiel de carry en mid-game.",
    video: "https://youtu.be/Y_AiAoVZkTQ",
  },
  {
    name: "Mordekaiser", rating: "lose", laning: "Difficile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Son Q est plus étroit en early, plus facile à esquiver. Évite de laisser les sbires qu'il peut farmer. Provoque son silence avant son ultime pendant un gank pour qu'il soit bas en vie. Le QSS ne fonctionne pas contre son ultime.",
    howTo: "Un all-in niveau 2 est possible s'il ne respecte pas. Esquive son E (facile avec de l'anticipation). Avant le 6, le matchup est un vrai duel de skill sur l'esquive des sorts. Après le 6, tout se complique fortement.",
    video: "https://www.youtube.com/shorts/cXfKICSvbqU",
  },
  {
    name: "Nasus", rating: "win", laning: "Facile-moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran épée",
    tips: "Garde ton Q pour son ralentissement. Surveille son ultime pour faciliter le 1v1. Sois prudent en utilisant ton ultime s'il n'a pas encore utilisé le sien. Empêche-le de farmer librement.",
    howTo: "Abuse des niveaux 1 à 5 avec de l'agressivité, du freeze ou un dive avec ton jungler. Gagne l'early pour snowballer. Il devient fort en mid-game mais tu gardes le contrôle grâce à ton ultime. Tu prends l'avantage sur la durée.",
    video: null,
  },
  {
    name: "Olaf", rating: "skill_garen", laning: "Moyenne-difficile",
    skillOrder: "E > Q > W", altSkillOrder: "Q > E > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Esquive les lancers de sa hache à distance. Il est faible quand sa hache est loin de lui. Prends en compte le bouclier vérifié par son ultime. Surveille sa régénération massive à bas PV.",
    howTo: "Évite les combats prolongés, il t'use facilement sur la durée. Ton ultime et l'Ignite sont très efficaces bien utilisés contre lui, ils empêchent son gameplay.",
    video: "https://www.youtube.com/shorts/jE-TE1rEWsY",
  },
  {
    name: "Ornn", rating: "skill_garen", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Ton silence empêche son deuxième ultime. Son souffle E déclenche sa passive si le dernier tick te touche, passe à travers en te positionnant bien. Surveille son burst de combo après le 6.",
    howTo: "Avantage en skill avant le 6, la balance penche en sa faveur après ses items grâce à sa passive. Après le 6, plus jouable car il manque de sustain. Le mid-game est le meilleur moment pour faire la différence grâce à ta mobilité. Reste focus sur le farm.",
    video: null,
  },
  {
    name: "Pantheon", rating: "skill_opponent", laning: "Difficile",
    skillOrder: "Q > E > W", altSkillOrder: "W > Q > E",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Signale quand il peut utiliser son ultime. Ne te fais pas piéger par son E : il peut annuler les dégâts de son ultime même en flashant juste avant l'impact.",
    howTo: "Le poke en early est vraiment difficile s'il joue bien. Survis à la lane, punis ses mauvais trades, fais la différence en mid-game. Tu scales — priorise ton W contre le combo poke/bonus de Q.",
    video: "https://youtu.be/haop4UabZYI",
  },
  {
    name: "Poppy", rating: "win", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Marche sur sa pièce passive pour l'annuler. Recule quand sa passive est disponible, elle va s'en servir pour farmer. Surveille le stun de son mur et utilise ton W si ça arrive. Elle a un bon potentiel de dive.",
    howTo: "Mets la pression en avançant pour la forcer à utiliser son Q. Elle est solide en lane avec de bons dégâts, joue sur le timing de ses cooldowns. Tu scales mieux qu'elle.",
    video: null,
  },
  {
    name: "Quinn", rating: "skill_opponent", laning: "Moyenne",
    skillOrder: "Q > W > E", altSkillOrder: "W > Q > E",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Son E annule ton Q, son aveuglement annule ton ultime. Elle est fragile avec peu de dégâts en early. Elle revient vite grâce à son ultime, ne te fais pas surprendre. Reste près des murs pour éviter d'être déplacé par son E.",
    howTo: "Impossible de la tuer en lane sauf grosse erreur de sa part après le 6. Concentre-toi sur le farm. Signale un maximum ses roams. D'autres matchups te donnent un meilleur scaling.",
    video: null,
  },
  {
    name: "Renekton", rating: "skill_even", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran épée",
    tips: "Surveille son ultime si tu comptes utiliser le tien (sauf si tu es réduit au silence). Les Tabis sont un bon achat ici.",
    howTo: "Il est puissant en early-mid, mais ton kit le contre bien, notamment le stun de ton W-E. Aux niveaux 1 à 3 avec une Doran épée, un combo complet peut suffire à l'éliminer. Trade prudemment en fonction de sa jauge de fureur. Surveille son all-in après le 6 : il te faut soit tuer, soit désengager.",
    video: null,
  },
  {
    name: "Rengar", rating: "win", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran épée ou Casque de faucheur",
    tips: "Surveille la régénération surprise de son W. Les Tabis contrent son burst sans être obligatoires. Fais attention en posant des wards dans les buissons.",
    howTo: "Reste loin des buissons, freeze près de la tourelle. Il est fort avant le 6, évite les embuscades. Après le 6, tu prends progressivement l'avantage.",
    video: null,
  },
  {
    name: "Riven", rating: "skill_garen", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran épée",
    tips: "Utilise ton Q pendant son troisième Q. Reste derrière elle pendant son E pour traverser son Q. Surveille l'affichage de ses stacks de Q en haut à gauche quand tu cliques dessus.",
    howTo: "Le matchup tourne autour du spacing et de l'exploitation de ses cooldowns. Le niveau de la Riven adverse change beaucoup la donne aux hauts niveaux. Elle est forte au niveau 1, surveille ses resets de Q. Son burst au niveau 6 est dangereux, surtout avec Ignite. La gestion de ton W est cruciale.",
    video: null,
  },
  {
    name: "Rumble", rating: "lose", laning: "Très difficile",
    skillOrder: "Q > E > W", altSkillOrder: "W > Q > E",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Sa zone rouge (33-100% de chaleur) inflige plus de dégâts, ses autos-attaques sont boostées en surchauffe. Son E réduit ta résistance magique.",
    howTo: "L'early est brutal, tiens bon jusqu'au niveau 11 ou ton premier item. Il ne peut pas reculer et utiliser son Q en même temps, mets-le sous pression. Après le 6, un kill est possible sur erreur de sa part. Tu prends l'avantage au scaling.",
    video: null,
  },
  {
    name: "Sejuani", rating: "win", laning: "Moyenne",
    skillOrder: "E > Q > W", altSkillOrder: "Q > E > W",
    summoners: "Flash / Ignite", starterItem: "Au choix",
    tips: "Fais tomber sa passive avant de trader. Recule avant qu'elle n'atteigne 4 stacks et ne stun. Surveille son burst au niveau 6, notamment avec Ignite.",
    howTo: "Un matchup assez simple à condition de bien jouer : c'est l'un de tes meilleurs face à une Sejuani top lane.",
    video: null,
  },
  {
    name: "Sett", rating: "skill_even", laning: "Difficile",
    skillOrder: "Q > W > E", altSkillOrder: "W > Q > E ou Q > E > W",
    summoners: "Flash / Ignite", starterItem: "Doran épée ou Doran bouclier",
    tips: "Anticipe son E avec ton W-E ou ton W seul. À bas PV il régénère vite en plein combat, les trades à 50% de vie ne valent pas le coup. Sans son W il est vulnérable. Son ultime n'annule pas ton E.",
    howTo: "Ne prends que des trades courts. Évite les dégâts de son W chargé. Après le 6, surveille les setups de dive. Ne trade pas en dessous de la moitié de ta vie sauf pour le tuer. Désengage vite après un trade.",
    video: "https://youtu.be/xz-eEhqpbPo",
  },
  {
    name: "Shen", rating: "skill_even", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Casque de faucheur ou Doran épée",
    tips: "Ne te place pas entre son épée et lui, sinon il gagne un Q boosté et un reset de cooldown sur sa passive. Utilise ton W-E contre son taunt. Signale son ultime niveau 6. Reste vigilant quand il cherche à ulti, et pousse quand il utilise sa téléportation.",
    howTo: "Tu peux démarrer par ton E pour gagner le niveau 1 si tu trades, ton Q fonctionne aussi. Avant le 6, son taunt joue en sa faveur. Après le 6, tu gagnes si tu esquives son E ou son combo W-E-E. Privilégie les trades longs, il est plus faible une fois son burst dépensé.",
    video: null,
  },
  {
    name: "Singed", rating: "win", laning: "Facile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Casque de faucheur",
    tips: "Ne le poursuis pas trop loin. Utilise ton Q pendant son flip. Tu peux acheter Cull s'il refuse le combat.",
    howTo: "En 1v1 tu gagnes si tu évites son poison. Il ne va pas chercher le combat et préfère l'impact carte ou le proxy pour gagner des ressources. Match son proxy s'il refuse la lane.",
    video: "https://www.youtube.com/shorts/P6ysAu-V8Mc",
  },
  {
    name: "Sion", rating: "skill_garen", laning: "Facile-moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Casque de faucheur",
    tips: "Ton silence annule son Q mais le cooldown retombe à 2 secondes. Un Sion Phase Rush peut te suivre même sous ta passive. Démarre par autoattaque-E ou juste E pour les dégâts. Positionne-toi pour empêcher son ultime de s'échapper.",
    howTo: "Il est faible en early à cause du scaling de sa passive. Abuse-en pour un kill ou pour installer la wave. Après le 6, sa passive revient vite. Un bon tempo est crucial en haut niveau.",
    video: "https://www.youtube.com/watch?v=judfCzVqCrg",
  },
  {
    name: "Skarner", rating: "skill_even", laning: "Moyenne-difficile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Au choix",
    tips: "Ton W rend son ultime inutile en 1v1. Ton silence annule son E. Il peut te traîner à distance, ce qui facilite ses ganks. Ses nombreux ralentissements permettent de prolonger la lane à son avantage.",
    howTo: "Avant le 6, abuse de ses cooldowns absents, mais ça devient plus dur après son premier retour en base. Un Cristal de rubis aide à tenir les trades. Surveille les possibilités de flanc via les murs en teamfight.",
    video: null,
  },
  {
    name: "Tahm Kench", rating: "skill_even", laning: "Moyenne-difficile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Au choix",
    tips: "Ton Q annule son W, garde-le pour t'échapper. Ton E continue d'infliger des dégâts même dans son ultime. N'utilise pas ton W contre son ultime, c'est un gaspillage. Son Q lui rend de la vie s'il touche. Écoute le signal de son échappée au W.",
    howTo: "L'early est difficile. Pousse en restant derrière tes sbires, évite son Q. Un abus de niveau reste possible en early. Son ultime est fort en 1v1 tôt dans la partie. Tu prends l'avantage au scaling.",
    video: null,
  },
  {
    name: "Teemo", rating: "lose", laning: "Très difficile",
    skillOrder: "Q > E > W", altSkillOrder: "Q > W > E",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Il se cache partout, surtout au niveau 1 et à bas PV. Évite les buissons et les déplacements hors chemin. Les ganks de ton jungler sont risqués à cause de ses champignons. Le dewarding reste possible.",
    howTo: "Encaisse l'early, punis la surextension comme face à tout champion à distance. Le niveau 6 ouvre des angles de kill via Flash + ultime. Surveille son aveuglement, ses champignons et le Bone Plating.",
    video: "https://youtu.be/6cYbycHtG_c",
  },
  {
    name: "Trundle", rating: "skill_opponent", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran épée ou Doran bouclier",
    tips: "Un bon setup de gank existe contre toi. Tu ne peux généralement pas combattre pendant son ultime : fuis et temporise si possible. Évite de trop stacker de résistances, son ultime les réduit.",
    howTo: "Engage à l'E, recule, fuis au Q après un combo, surtout s'il ulti (quasiment invincible en 1v1). C'est une menace de split push à surveiller.",
    video: null,
  },
  {
    name: "Tryndamere", rating: "lose", laning: "Très difficile",
    skillOrder: "Q > E > W", altSkillOrder: "Q > W > E",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Utilise ton ultime en synchro avec un tir de tourelle. Il est plus faible avec peu de rage. Freeze pour l'empêcher de farmer (situationnel). Surveille la régénération de son Q avant son ultime.",
    howTo: "En Conquérant, bouge avant le niveau 6 et surveille l'Ignite. En Phase Rush, privilégie le scaling et le farm. Après le 6, évite les dives et échange les ultimes quand c'est possible. Il split push fort : neutralise-le en jouant l'autre côté de la carte.",
    video: null,
  },
  {
    name: "Urgot", rating: "skill_even", laning: "Moyenne-difficile",
    skillOrder: "E > Q > W", altSkillOrder: "Q > E > W",
    summoners: "Flash / Ignite", starterItem: "Doran épée",
    tips: "Fais-le gaspiller son E facilement ou punis-le avec ton W. Il manque presque totalement de sustain. Les Tabis réduisent nettement ses dégâts. Ton Flash contre facilement son ultime.",
    howTo: "Avance avec la wave au niveau 1, évite le premier buisson. Engage à l'E si tu attaques, réponds avec ton E s'il engage. Cherche un all-in tôt avant que le poke ne s'accumule. Snowballe ton avantage. Le mid-game penche en sa faveur.",
    video: null,
  },
  {
    name: "Varus", rating: "lose", laning: "Très difficile",
    skillOrder: "Q > W > E", altSkillOrder: "Q > E > W",
    summoners: "Flash / Ghost", starterItem: "Doran bouclier",
    tips: "Surveille s'il joue la sort d'invocateur Barrière.",
    howTo: "Ne le 1v1 pas. Ghost te permet de suivre un gank, d'appliquer ton combo et de désengager en sécurité sans mourir. Ses dégâts en early sont absurdes : joue ultra safe et évite de te faire toucher par 3 marques de son E.",
    video: null,
  },
  {
    name: "Vayne", rating: "lose", laning: "Très difficile",
    skillOrder: "Q > W > E", altSkillOrder: "Q > E > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Son E a 20 secondes de cooldown en early : all-in en plusieurs phases. Cache-toi dans les buissons de lane tôt pour forcer le warding et créer du danger de gank. Évite de bâtir trop de résistances inutiles.",
    howTo: "L'early est difficile, mets la pression quand possible en punissant ses erreurs de placement. Tu manques d'avantage en early comme en late, la différence se fait surtout en mid-game. Note que Vayne top n'est pas universellement forte.",
    video: null,
  },
  {
    name: "Vladimir", rating: "skill_even", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "Q > W > E",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Recule quand son Q est chargé. Surveille sa régénération, un 1v1 peut vite tourner en sa faveur.",
    howTo: "Tout dépend de son setup : Conquérant/Ghost est faible en early, Æry/Ignite est menaçant. Après le niveau 11, l'avantage penche légèrement pour toi. Punis la surextension. Surveille son combo one-shot ultime + Ignite.",
    video: null,
  },
  {
    name: "Volibear", rating: "skill_even", laning: "Moyenne-difficile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Utilise ton W-E si tu es stun. Son W marque et lui rend beaucoup de vie s'il le réactive. Recule avant un deuxième W ou tu perds le trade. Surveille la synergie de son ultime, il régénère si les deux ultimes sont simultanés.",
    howTo: "Esquive son E (prévisible, gros dégâts). Les trades tournent autour de l'application de son combo stun ; ton silence avant ses sorts permet un bon trade court. Il a généralement l'avantage en 1v1.",
    video: null,
  },
  {
    name: "Warwick", rating: "skill_even", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Il est quasi impossible à tuer en trade grâce à sa régénération. À bas PV sa régénération augmente encore, ne te fais pas piéger. Il joue souvent Barrière (utilisable même sous silence). Il est très fort en 2v2 et 2v1.",
    howTo: "Un bon Warwick est increvable en lane : sache distinguer ses baits de ses erreurs. Avant le 6 c'est très technique. Les trades longs se perdent toujours après son burst. Il pousse pour se régénérer.",
    video: null,
  },
  {
    name: "Wukong", rating: "win", laning: "Facile-moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Au choix",
    tips: "S'il active son W pendant ton Q, ton Q le touche quand même. En all-in, garde ton Ignite pour son silence pour éviter le clone et révéler son vrai lui s'il active son W.",
    howTo: "Au niveau 1, s'il utilise son E il gagne en vitesse d'attaque et remporte les trades. Au niveau 3+, c'est un vrai duel de skill : tu gagnes si tu combos avec ton W, tu perds s'il poke/space avec son W. Au niveau 6 même logique — il burst fort à ce niveau.",
    video: null,
  },
  {
    name: "Yasuo", rating: "skill_even", laning: "Difficile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Utilise ton Q pendant sa tornade à courte distance pour éviter son ultime. Il manque de fuite s'il est loin des vagues de sbires.",
    howTo: "Il a de bons DPS, évite les trades longs. Joue près de ta tourelle en early. Après le 6, tout dépend du spacing. S'il gagne le tempo sur ton W, recule ou tu perds le trade. Ton silence le contrôle bien en teamfight.",
    video: null,
  },
  {
    name: "Yone", rating: "skill_even", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier ou Doran épée",
    tips: "Utilise ton Q pendant son troisième Q au corps-à-corps. Punis-le s'il utilise son Q sans te toucher.",
    howTo: "Il a de bons DPS, évite les trades longs. Après le 6, le spacing détermine l'issue du combat. S'il gagne le tempo sur ton W, recule ou tu perds. Ton silence le contrôle bien en teamfight.",
    video: null,
  },
  {
    name: "Yorick", rating: "lose", laning: "Moyenne-difficile",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Ses goules donnent des stacks à son W ; last-hit rapidement mais ça réinitialise sa passive si tu l'attaques. Sa cage E signifie un trade perdu, il faut la baiter/esquiver complètement. Son Q lui rend beaucoup de vie.",
    howTo: "L'early tourne autour de l'esquive de son E et de sa cage. Le proxy le contre bien si tu maîtrises la technique. Il est faible avant son ultime. Le mid/late game dépend beaucoup du macro.",
    video: null,
  },
  {
    name: "Zac", rating: "skill_garen", laning: "Moyenne",
    skillOrder: "Q > E > W", altSkillOrder: "E > Q > W",
    summoners: "Flash / Ignite", starterItem: "Doran bouclier",
    tips: "Marche sur ses blobs pour les faire disparaître. Son sustain via les blobs est énorme, ne te fais pas piéger. Les passifs après un kill sont risqués si les blobs ne sont pas détruits (ils reviennent). Bon setup de gank pour lui.",
    howTo: "Un bon Zac est dur à tuer grâce à son sustain, un peu comme Warwick. Un bon trade en early est possible avec Conquérant. Son ultime au niveau 6 a une grosse valeur. Le matchup dépend beaucoup du niveau du Zac adverse.",
    video: null,
  },
];
